### ISSUE TITLE
[Feature Request] 特性请求清单

### ISSUE THREAD

**Issue by Just2Archi** [HsiaohuiHsiang/KafkaRefresh#35]
非常不错的库，感谢作者开源。看到README中有FR的入口，所以进来做一下贡献，仅供参考（想必作者重新造轮子肯定也是对于现有的不满）。

1. 自动加载目前是需要到底部才会触发。可否加一个临界值，比如距离底部1000的时候就触发。
2. ReplicatorDot 样式初始状态的点点太小，能不能设置大一点。
3. 请求添加一个类似微信小程序下拉的那种效果，也是3个点。(下拉的时候间距会变大，达到临界值的时候颜色稍微改变，加载中会有一个加载效果)
4. 最少的加载时间的设置，比如REST接口平均加载只需要50ms, 但是一个动画周期需要600ms，这就会导致下拉后几乎马上就完成了，就看不到动画（并不是说一定要看看动画，而是这给用户的体验不太好，用户会感觉操作没效果一样）

以上，仅供大大参考。

**Comment by OpenFeyn** [comment]
很感动这样清晰的描述。见过太多...哎...你懂的...
依次回答：
1、自动加载的临界值，这个点也是在最新的版本中才加上，我更偏向开发者主动控制这部分。原因是：a。开发者能主动监听用户的滑动速率，触发偏移值；b。加上该功能后，多数使用者必然不如何参看文档，只知道一味调用API停止刷新，势必又会引发一系列非该库原因的issue；
2、可以；请给一些时间，实在忙到...
3、嘿嘿，还是需要一些时间。心里话是：更想看到有其他人（比如你）一起帮忙，不仅仅是issue，而是更多的pull request。因为开放了一些接口，足够实现提出的要求；
4、非常欣赏提出的第四点，相当好的建议，我希望能在我空下来时，慢慢完善这点。手里头弄着php，分身无术，好累哉！
谢谢

**Comment by abellee** [comment]
@OpenFeyn 辛苦辛苦
1、我觉得可以设置成一个选项，比如现在算的是滚动到底部才触发，那可以增加一个变量，默认为0 开放出来设置就可以达到提前加载的效果了。
3、好像可以用CustomHeader实现吧
4、手动触发endRefresh的时间往后不就可以了吗
