### ISSUE TITLE
上拉刷新加载数据后偏移有问题

### ISSUE THREAD

**Issue by xiaozhouboy** [HsiaohuiHsiang/KafkaRefresh#63]
- iOS 12.4、12.1；
- KafkaRefresh最新版本

[设置了tableView.estimatedRowHeight](url) = UITableViewAutomaticDimension;

**Comment by zhoushaomon** [comment]
![屏幕录制 2020-03-09 下午6 09 58](https://user-images.githubusercontent.com/15812647/76203530-c23e3e00-6231-11ea-9cee-5398021212f1.gif)

**Comment by HsiaohuiHsiang** [comment]
从本地查看了几个机型。即使设置了UITableViewAutomaticDimension，也未复现。

**Comment by CherryIce** [comment]
有问题的 
1、 [weakSelf.tableView.footRefreshControl endRefreshing];放在 [weakSelf.tableView reloadData];前面，加载数据分页够多的时候就会出现上拉数据明显跳动 
2、 [weakSelf.tableView.footRefreshControl endRefreshing];放在 [weakSelf.tableView reloadData];后面，就会出现上拉刷新时候页面闪动
初步认为是- (void)setScrollViewToOriginalLocation:(dispatch_block_t)completion中的self.scrollView.insetBottom = self.presetContentInsets.bottom;这里的处理问题
