### ISSUE TITLE
【bug】 上拉加载更多时，列表偏移跳动

### ISSUE THREAD

**Issue by zzzzzyijie** [HsiaohuiHsiang/KafkaRefresh#64]
- iOS版本；
- KafkaRefresh版本（最新版）；

如Demo所示

如果加载完毕直接调用endRefreshing：
 [weakSelf.tableView reloadData];
 [weakSelf.tableView.footRefreshControl endRefreshing];
  
 那么列表会偏移跳动。

即使使用（如Demo的写法） 
[weakSelf.tableView reloadData];
[weakSelf.tableView.footRefreshControl endRefreshingWithAlertText:@"Did load successfully" completion:^{
                [weakSelf.tableView reloadData];
}];

如果快速拉到底部（AlertText还没消失），这时列表也会跳动，这样滑动不流畅。

（ps: 所提供的demo可以重新以上现象）

**Comment by HsiaohuiHsiang** [comment]
🚀  KafkaRefresh (1.4.8) successfully published
