### ISSUE TITLE
没数据后endRefreshingAndNoLongerRefreshingWithAlertText 刘海屏没适配

### ISSUE THREAD

**Issue by zzzzzyijie** [HsiaohuiHsiang/KafkaRefresh#66]
如Demo的图所示
![Snip20200510_1](https://user-images.githubusercontent.com/17098514/81501795-ca3b5c80-930c-11ea-9e58-93999c5e1a26.png)

**Comment by zzzzzyijie** [comment]
系统 ： iOS 13

**Comment by zzzzzyijie** [comment]
请问这个怎么适配的？没找到相关属性

**Comment by HsiaohuiHsiang** [comment]
自己布局问题

**Comment by zzzzzyijie** [comment]
感谢回复。
这是在您提供的deme里截的图。
布局是没问题的，也都是普通的self.tableView.frame = self.view.bounds;
不管刘海屏或非非刘海屏都这样。
是否本来是这样设计的？ （ 始终停留在屏幕的底部，只有在上拉的时候才看到？

**Comment by zzzzzyijie** [comment]
感谢回复。
这是在您提供的deme里截的图。
布局是没问题的，也都是普通的self.tableView.frame = self.view.bounds;
不管刘海屏或非非刘海屏都这样。
是否本来是这样设计的？ （ 始终停留在屏幕的底部，只有在上拉的时候才看到？

**Comment by HsiaohuiHsiang** [comment]
对的。

**Comment by zzzzzyijie** [comment]
> 对的。

如果这样设计的话，在刘海屏不会觉得很奇怪吗（如上图所示），个人观察主流App似乎都会把「暂无数据」的文案全显示出来，不考虑把这种情况加上嚒？
