### ISSUE TITLE
auto refresh for header without pull and release

### ISSUE THREAD

**Issue by fukemy** [HsiaohuiHsiang/KafkaRefresh#69]
hi, i tried to set 
```
        messagesCollectionView.headRefreshControl.autoRefreshOnFoot = false
```
but it seem not working, can u help

**Comment by HsiaohuiHsiang** [comment]
hi, headRefreshControl has no auto refresh function, only footRefreshControl

**Comment by HMWDavid** [comment]
I think the HeadRefreshControl should also be supported
