### ISSUE TITLE
当数据为空，上拉加载时footRefresh显示在上面位置

### ISSUE THREAD

**Issue by xiaozhouboy** [HsiaohuiHsiang/KafkaRefresh#70]
- iOS 14.0；
- KafkaRefresh 1.5.0；
- 当数据为空，上拉加载时footRefresh显示在上面位置，如何让它显示在屏幕下面，类似于headRefresh的位置

**Comment by HsiaohuiHsiang** [comment]
一般的，在首次调用成功后，才给ScrollView配备刷新控件；虽然主动调用控件刷新方法也可达到加载数据的效果，但屏幕会出现刷新效果，这并不合时宜

**Comment by HsiaohuiHsiang** [comment]
一般的，在首次调用数据成功后，才给ScrollView配备刷新控件；虽然主动调用控件刷新方法也可达到加载数据的效果，但屏幕会出现刷新效果，这并不合时宜
